FROM mcr.microsoft.com/devcontainers/typescript-node

LABEL org.opencontainers.image.source=https://github.com/fabian-lohauss/CloudDeploymentFramework
LABEL org.opencontainers.image.description="CloudDeploymentFramework DevContainer image"
LABEL org.opencontainers.image.licenses=MIT