FROM mcr.microsoft.com/devcontainers/typescript-node

LABEL org.opencontainers.image.source=https://github.com/fabian-lohauss/DeploymentFramework
LABEL org.opencontainers.image.description="DeploymentFramework DevContainer image"
LABEL org.opencontainers.image.licenses=MIT